name: spell-check
on:
  pull_request:
  push:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # https://github.com/streetsidesoftware/cspell-action
      - uses: streetsidesoftware/cspell-action@v3
        with:
          incremental_files_only: true
          config: '/cspell.json'