name: spell-check
on:
  pull_request:
  push:

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: check for wrapped links
        run: |
          python scripts/wordlist.py check wordlist.txt
      - uses: actions/setup-node@v3
        name: Run spell check
        with:
          node-version: "18"
      - run: npm install -g cspell
      - run: cspell --config ./cspell.json